// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChxt9MC19V6rRcM75NnYb93v9KgGVExCw',
    appId: '1:123810129294:web:9b66ec2d5b62d050f470df',
    messagingSenderId: '123810129294',
    projectId: 'home-de76c',
    authDomain: 'home-de76c.firebaseapp.com',
    databaseURL: 'https://home-de76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-de76c.firebasestorage.app',
    measurementId: 'G-GSGK1YJ1H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoTSM9admmxyEklrnSomJgMaMuc2l4uY',
    appId: '1:123810129294:android:d1c3f0b702a0c3dff470df',
    messagingSenderId: '123810129294',
    projectId: 'home-de76c',
    databaseURL: 'https://home-de76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-de76c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADJ4-h-ANjLhw9EmTa_CBTMpje--nTzcE',
    appId: '1:123810129294:ios:f04db702e359e249f470df',
    messagingSenderId: '123810129294',
    projectId: 'home-de76c',
    databaseURL: 'https://home-de76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-de76c.firebasestorage.app',
    iosClientId: '123810129294-camhvqqmmf15ngej57t8nakqg27b3pr6.apps.googleusercontent.com',
    iosBundleId: 'CFBundleShortVersionString',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADJ4-h-ANjLhw9EmTa_CBTMpje--nTzcE',
    appId: '1:123810129294:ios:f78e4f3700500414f470df',
    messagingSenderId: '123810129294',
    projectId: 'home-de76c',
    databaseURL: 'https://home-de76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-de76c.firebasestorage.app',
    iosClientId: '123810129294-iujiltmuembc9o6khtnt8lokvlmmf8tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChxt9MC19V6rRcM75NnYb93v9KgGVExCw',
    appId: '1:123810129294:web:b1e0fe5986df6bbef470df',
    messagingSenderId: '123810129294',
    projectId: 'home-de76c',
    authDomain: 'home-de76c.firebaseapp.com',
    databaseURL: 'https://home-de76c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-de76c.firebasestorage.app',
    measurementId: 'G-56EKCYLWZD',
  );
}
